apiVersion: v1
kind: Service
metadata:
  name: dcr-headless
spec:
  clusterIP: None
  selector:
    job-name: dcr
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dcr
data:
  register.sh: |
{{ tpl (.Files.Get "scripts/register.sh") . | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dcr
  labels:
    app: dcr
  annotations:
    # Hooks are added to the job to ensure that:
    #   - The job is executed after the chart is installed, upgraded or synced
    #   - ArgoCD does not expect the job to exist after it's execution
    #   - The job is executed before the next hook is executed (if any)
    #   - The job is deleted if it still exists when the chart is upgraded or uninstalled
    # ArgoCD hooks
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
    # Helm hooks
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: {{ .Values.ttl_seconds }}
  template:
    spec:
      containers:
        - name: register
          image: {{ .Values.image }}
          command: ["/bin/sh", "/mnt/dcr/register.sh"]
          env:
            - name: SECRET_NAME
              value: {{ include "secret.name" . | quote }}
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: DCR_REGISTRATION_URL
              value: {{ .Values.registration_url | quote }}
            - name: REQUEST
              value: {{ .Values.request | toJson | quote }}
            - name: SECRET_KEYS
              value: {{ include "secret.keys" . | fromYaml | toJson | quote }}
          volumeMounts:
            - name: dcr-volume
              mountPath: /mnt/dcr
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      serviceAccountName: {{ include "service_account.name" . }}
      volumes:
        - name: dcr-volume
          configMap:
            defaultMode: 493
            name: dcr
      restartPolicy: Never

